name: End-to-end tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:smoke
      
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Cypress-Reports
          path: cypress/reports/html/index.html
          if-no-files-found: ignore

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.MY_SECRET }}
          publish_dir: cypress/reports/html
